[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
upload_speed  = 57600
board_build.flash_mode = dio
board_build.flash_freq = 40m
board_build.flash_size = 4MB
upload_flags =
  --no-stub
  --before
  default_reset
  --after
  hard_reset
build_flags =
  -DCORE_DEBUG_LEVEL=1
